version: "3.5"

services:
  gve_devnet_webex_calling_detailed_report:
    image: ghcr.io/gve-sw/gve_devnet_webex_calling_detailed_report:latest
    container_name: gve_devnet_webex_calling_detailed_report
    environment:
      - <ENV VARIABLE NAME>=<VALUE>
    volumes:
      - config.yaml:/app/config.yaml
    restart: "always"
